### ISSUE TITLE
Mass Effect 1 & 2

### ISSUE THREAD

**Issue by mirh** [EliotVU/Unreal-Library#18]
Partial support is already in
https://github.com/Dybuk/Unreal-Library/compare/3135e3129f5c00773d5724543b2d54b08a21b7d3...8e29ae6197b6bc756b0032dfe382b1ee9bf83a38 and https://github.com/Dybuk/Unreal-Library/commit/77ffede601194e4df2250b0677db262a634f657f

**Comment by EliotVU** [comment]
I would integrate those changes if they were to make a pull request.
Although some of their changes look like they might break the compatibility with other games.

**Comment by Dybuk** [comment]
Yeah there is a reasonable chance if they were pulled as they are some other games may break. I found the build numbers were slightly wrong for for some of the features and had to tweak to get them to work. I could tweak all the changes and wrap them with "if mass effects".

With those changes Mass Effect 2 and Mass Effect 1 Xbox come out pretty good. Mass Effect 1 PC still had a problem where the curly brackets didn't quite line up properly. I never did get to the bottom of it. It was functional enough for my needs though.

I didn't require Mass Effect 2 Xbox, so never tried that.

**Comment by EliotVU** [comment]
Better late than never? :) I recently pushed a old branch of code with support for all Mass Effect games, although not all of those have been battle tested (at least yet)

3e1dfb562f9e6e9d1c2bc3c7c7bfce9fc1a7adf3
48b427f174f399222e2039cf43a368ed54fbf00a

I couldn't disassemble `masseffect.exe` until the Legendary edition came along, so the support was concluded from that build.
