### ISSUE TITLE
Missing UE Explorer solution

### ISSUE THREAD

**Issue by VendorX** [EliotVU/Unreal-Library#19]
If this project is still alive I can write decompression block but to do this I need entire source code - not only UElib. Let me know soon as possible.

**Comment by EliotVU** [comment]
Hey, I can give you an invite to the bitbuckets repository if you want. Although I'm sure you can implement this without the front-end :)

**Comment by VendorX** [comment]
Yeah, scratch that ... I've implemented Decompression and support for UC2, AA3 and AA4 - AA4 needs a big fix on SerialiseExpr ... good work on this one BTW.
I can send you Decompression files so you can update UEE.
If I may: Try to implement StaticLoadObject for ImportTable.
