### ISSUE TITLE
LZX and ZLIB compression ...

### ISSUE THREAD

**Issue by VendorX** [EliotVU/Unreal-Library#20]
... I need some different files for testing (LZX: Xbox, ZLIB: PS) - if you guys can send me, I will appreciate.

Eliot@ LZO decompression is ready - I can send you the files (...or just give me the access...).
After decompression Americas Army 4 is fully supported.

So far:
AAO250
AAO285
AA3
AA4
Unreal Championship 2
Mass Effect 1

**Comment by EliotVU** [comment]
Can you make a pull request? Thanks.

I may have one, albeit not sure, most of my test files are unorganized.

**Comment by VendorX** [comment]
I'm not sure if I understand ... you want me to make a pull for requested files? ... or decompression implementation?

BTW: you know that there will be no one to vote right? ... forum is practically dead, so this project, Only few ppl still care about it.
Three (or more) years ago I told you that I could implement decompression ...

**Comment by EliotVU** [comment]
I want you to make a pull request for the decompression implementation. 

This has nothing to do with voting :)

**Comment by EliotVU** [comment]
Closing as stale. Looking back at this I have to apologize for coming across as rude, I didn't mean to sorry!
