### ISSUE TITLE
FixToken() but for Flags?

### ISSUE THREAD

**Issue by Glichy** [EliotVU/Unreal-Library#24]
Hey, would you mind adding something like FixToken() but for Flags, so they can be replaced easily?
I don't really know C# but i have had some progress adding support for a game.
Thanks

**Comment by EliotVU** [comment]
I'm sorry I didn't respond to this, but due its age I'm closing this issue, but nonetheless a similar solution has been implemented see https://github.com/EliotVU/Unreal-Library/blob/78179bcf8d1267c811ea63975f19a65dc588c1bd/src/UnrealFlags.cs#L6
