### ISSUE TITLE
DD2 Support

### ISSUE THREAD

**Issue by TooMuchLegacy** [EliotVU/Unreal-Library#25]
```
                /// <summary>
                /// 688/117
                /// </summary>
                [Build(688, 117)]
                DungeonDefenders2,
```

SerialOffset is always 0 for export table items.

How to calculate:
SerialOffset = Package.HeaderSize + Sum of SerialSize of previous items
or:
```
#if DUNGEONDEFENDERS2
            if (stream.Package.Build == UnrealPackage.GameBuild.BuildName.DungeonDefenders2)
            {
                if (stream.Package.Exports.Count == 0)
                {
                    SerialOffset = (int)(stream.Package.HeaderSize);
                }
                else
                {
                    var PreviousExportTableItem = stream.Package.Exports[stream.Package.Exports.Count - 1];
                    SerialOffset = (int)(PreviousExportTableItem.SerialOffset+ PreviousExportTableItem.SerialSize);                    
                }
            }
#endif   
```

Sorry for leaving this as an issue. I can branch when I have the time; if needed. 
Maybe also someone else has a better idea how to do the trick? Espiacally because of the long->int casting ...

**Comment by EliotVU** [comment]
Thanks, I'll be pushing a fix for this game soon!

Better late than never :D

**Comment by TooMuchLegacy** [comment]
The good old times when I digged through dd2. :laughing: 
Thanks for bringing back the memories and especially for maintaining this project.
:1st_place_medal:
