### ISSUE TITLE
Chivalry Medival Warfare - not fully supported?

### ISSUE THREAD

**Issue by zaee-k** [EliotVU/Unreal-Library#28]
Hello and thank you for such a lovely software!

I've tried to fix a bug in existing CWM mod, but upon opening the .u file, I get red colors on objects with info "Deserialization failed by the following exception" regarding end of stream read.

From your forums I see that:

> XCom: Enemy Unknown
Bioshock Infinite
Chivarly: Medieval Warfare
Are supported.

Did something changed since the last supported version? Do I need to enter some custom Version/Licensee?

Regards

**Comment by EliotVU** [comment]
Thanks! 

Sorry for not responding at the time, however I cannot reproduce this issue.

If this is still relevant to you or someone else, I suggest giving UE Explorer version 1.3 a try, which is using a newer UELib with some UE3 support improvements.
