### ISSUE TITLE
Support: Bioshock

### ISSUE THREAD

**Issue by EliotVU** [EliotVU/Unreal-Library#3]
Partially supported but needs fixes.

**Comment by PaulBGD** [comment]
Hey, I'm currently looking into bioshock. What are the big things you noticed back when you made this issue?

**Comment by EliotVU** [comment]
Hey, There was one issue that I can still remember, it was an issue where UE Explorer couldn't tell the difference between an opcode that would lead to a typing cast from a Native function call.

e.g. Native function calls were seen as a type conversion, normally there are some op codes to tell the difference but in Bioshock they seem to have merged, but I never looked much further into it than that.

**Comment by PaulBGD** [comment]
Hot, thanks!
