### ISSUE TITLE
Running UE via command line?

### ISSUE THREAD

**Issue by adrianom-gh** [EliotVU/Unreal-Library#31]
Thanks so much for this decompiler! It's been working wonders. I was curious to know if you can run this via command line? I'm looking to write a batch script that will export a bunch of .uc files from a .upk.

**Comment by EliotVU** [comment]
You're welcome! 

Fortunately there is indeed a way to launch UE Explorer via its console form :)

Arguments:


    <file_path> (Optional)
    -console : Launches UE Explorer as a console window displaying its live-log.
        -silent : The console window will automatically close when the task completes.
         
        -export=classes or scripts : Exports all classes or scripts from the specified package.
        -newwindow : Open the file in a new UE Explorer window.


Example:


    "C:\Program Files (x86)\Eliot\UE Explorer\UE Explorer.exe" "C:\UT2004\System\Core.u" -console -export=classes
