### ISSUE TITLE
Argument Out of Range Exception when loading some Unreal Tournament 3 .u packages

### ISSUE THREAD

**Issue by BitCrusader** [EliotVU/Unreal-Library#38]
LoadFullPackage() fails on UObject::GetIndexObject() with the exception "Index was out of range. Must be non-negative and less than the size of the collection." - tested with both Engine.u and Core.u. Arkham Asylum's BmGame.u also fails in the same place after manual decompression.

**Comment by EliotVU** [comment]
Sorry for the late response, but I am unable to reproduce this issue in either UE Explorer nor the current state of this UELib.
