### ISSUE TITLE
Batman Arkham Knight - Support

### ISSUE THREAD

**Issue by HexPa5** [EliotVU/Unreal-Library#44]
Hey can you add support for this latest Rocksteady game? It contain a lot of unknown classes made by devs to register. I do sometimes Hex pathing so it may be helpful for our modding community also for reverse engineering, Please :)

**Comment by EliotVU** [comment]
This may be of interest: [https://github.com/EliotVU/Unreal-Library/commits/game-arkham](url), however there is still some work to do.

**Comment by EliotVU** [comment]
Please see https://github.com/EliotVU/Unreal-Library/releases/tag/1.3.0.0-Batman
