### ISSUE TITLE
XCOM issue with v1.3

### ISSUE THREAD

**Issue by Developer-Maker-Educator** [EliotVU/Unreal-Library#48]
When I try to load .upk files from the Long War or Long War Rebalanced mods for XCOM: Enemy Within (which, in my understanding, are pre-decrypted), I either get erroneous decompiled code, or I get an unhandled exception upon load.

If I load it in v1.27, it works fine. I don't have any further information currently, but if I can help track down this problem, please let me know how I can help.

**Comment by EliotVU** [comment]
Could you send me one of those files that cannot be opened?

On my side "XComStrategyGame.upk" is the only file that couldn't be opened in 1.3 but can be opened fine on the "develop" branch.

**Comment by Developer-Maker-Educator** [comment]
That's great! Thank you!
