### ISSUE TITLE
Support for Batman: Arkham Knight

### ISSUE THREAD

**Issue by Cult-7191** [EliotVU/Unreal-Library#51]
Hi EliotVU, I'm not very well-versed in programming or game development, but I'm an Arkham Knight modder who is sort of desperate to find new advances in Arkham modding. I've created several mods through hex editing and creating Config/DLC files to create new custom skins, but I know there are significantly more possibilities using UE Explorer. 

I would be extremely grateful if you could add further support for Batman: Arkham Knight as there is very little that is readable. 
Although, I don't want to bother you for long, Thanks for your time.

**Comment by EliotVU** [comment]
Hello, @Cult7191

I'm glad to hear you have a use for UE Explorer!

I took a look at the support for Batman4 and can confirm there's indeed not much data that UELib is able to decipher.
Support for Batman series is mostly limited to the older games, but fortunately I have been able to improve the support for Arkham Knight, which I'll push soon.
