### ISSUE TITLE
Index Out of Range error

### ISSUE THREAD

**Issue by Wastelander121** [EliotVU/Unreal-Library#54]
Thank you for creating this tool. It's helped us make massive strides in regards to modding quire a few games. However, when attempting to decompile certain unsupported classes, Unreal Explorer will display the following error: 

![image (1)](https://user-images.githubusercontent.com/29731570/205233877-14b3b7ae-ec68-46cc-b3d4-a195f12248a0.png)

If possible could you please look into seeing if this can be resolved? It would mean we could a lot more stuff such as editing Arkham's playable character packages which still contain a lot of cut content that we would like to restore. 

Thank you again for all the wonderful work you've done for all the modding communities.

**Comment by EliotVU** [comment]
Sure! :)

I'm currently working on a hotfix to resolve this problem, among other minor inconveniences.

**Comment by EliotVU** [comment]
Resolved! See https://github.com/UE-Explorer/UE-Explorer/releases/tag/1.3.1

**Comment by EliotVU** [comment]
Sneak peek :)

![image](https://user-images.githubusercontent.com/808593/206037785-1172aec8-c255-4a7f-a958-bffa97df5e34.png)
