### ISSUE TITLE
Feature - XXX Unreal console package

### ISSUE THREAD

**Issue by HexPa5** [EliotVU/Unreal-Library#61]
Hello do you have any plans to add new feature for loading packages from any Unreal 3 games ported to both 7th gen consoles? 
I know you may ask why we try mod games with Xenia Canary or with other emulators, so we want to move SkeletalMesh data from XXX to UPK by exporting and importing this tables in the same size in bytes. I hope it will work once you add support
But you don't need to do that I just asking.

**Comment by EliotVU** [comment]
XXX packages should work after decompressing, however if you are using the UE Explorer tool, you will have to configure it, to load packages in "console" mode, see the bottom right on UE Explorer.
