### ISSUE TITLE
The size is not equal how to bypass?

### ISSUE THREAD

**Issue by HexPa5** [EliotVU/Unreal-Library#62]
The size from content tab of SkeletalMeshes or Textures is not equal, it needs be the same size in bytes to import this new binary table. 
Do you know how to bypass this error in UE Explorer? I wish to import it with different size. Okey I should use Hex workshop or any Hex to localize start offsets and end offsets to replace with new data of the same file extension but I want to do this with UE explorer automatically. Also do you think it will work ingame? Do you think that most modern games has integrity checking for executables and game achieve files?

**Comment by EliotVU** [comment]
Sorry this is currently not possible with UE Explorer, you'll have to write your own code to instruct this library, or even mod the library itself, e.g. in theory you could change the SerialOffset and SerialSize in the export table and move your modified object's data to the end of the file, this way you won't have to move all the other objects within the package.

> Do you think that most modern games has integrity checking for executables and game achieve files?

This depends entirely on whether the game checks the packages for modifications to prevent cheats.
