### ISSUE TITLE
Crash while reading file from Battleborn

### ISSUE THREAD

**Issue by voltagex** [EliotVU/Unreal-Library#68]
```
System.ArgumentOutOfRangeException: 'Non-negative number required.
Parameter name: value
```

it seems like the wrong value is passed to `Skip`

[PoplarGame.zip](https://github.com/EliotVU/Unreal-Library/files/13388919/PoplarGame.zip) (original compressed file, in case I made a mistake while unpacking)

```
Package Version:874/78
Build:Unknown
Header Size: 2890256
Package Flags:3769106441
Names Count:19449 Names Offset:1697 Exports Count:27451 Exports Offset:694012 Imports Count:1557 Imports Offset:650416
GUID:af56e64a-0059-45fe-b272-7ed2023e498a
Generations Count:131
EngineVersion:69149103
CookerVersion:65683
CompressionFlags:0
PackageSource:4136500508
```

Edit: confirmed I extracted it as LZO correctly, even if I change UELib to read it as a Borderlands 2 file it still crashes.

**Comment by EliotVU** [comment]
I tinkered a bit, it works for the most part if you return before the deserializaing of "TextureAllocations" and set the build to Borderlands2
