### ISSUE TITLE
Support for "Tom Clancy's Splinter Cell"

### ISSUE THREAD

**Issue by EliotVU** [EliotVU/Unreal-Library#69]
[As requested](https://github.com/UE-Explorer/UE-Explorer/issues/37) Support package and UnrealScript decompilation for Splinter Cell 1.

**Comment by basketman125** [comment]
![error](https://github.com/EliotVU/Unreal-Library/assets/118209121/051f14eb-2308-43f6-beac-be2d35a2e3b3)
When I try to compile I get an error. How to fix it?

**Comment by EliotVU** [comment]
Sorry about that! Fixed.

**Comment by basketman125** [comment]
> Sorry about that! Fixed.

Thank you! File compiled now. But when i trying to load any *.u package i got a message:

![error1](https://github.com/EliotVU/Unreal-Library/assets/118209121/d8a8cf92-39de-47d8-bd7c-15bd0465b64d)

Stack Trace:
Thrown by:LoadPackage
   in UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   in UEExplorer.UI.ProgramForm.LoadFile(String fileName)

Message:
Field not found: "UELib.UnrealConfig.Platform".

If you need game files I can share them.

**Comment by EliotVU** [comment]
Sorry about that, basically that branch at the time was not compatible with UE Explorer. To use 1.4.0 with UE Explorer 1.3* recompilation is required.
