### ISSUE TITLE
[Need Help] How to repack resource files into UPK files?

### ISSUE THREAD

**Issue by jiuzhouhan996** [EliotVU/Unreal-Library#93]
I have a file names "MMO_UITitle.upk", then I use the tool by "UEViewer", I can get the resource files.
Now, I want to add some files in it, I need repack resource files into UPK files.
So thats my question, How to add a new file to an upk file?
If anyone knows, plz call me.

![1](https://github.com/user-attachments/assets/5ba064cf-d9f2-4e29-8f35-e9322d93f7c3)
![2](https://github.com/user-attachments/assets/9e9c0e79-ff5b-4b3a-82ed-c22ea2ae1fc9)

**Comment by EliotVU** [comment]
That would be nice, but is out of scope for this library.
